# Generated by Django 5.1.2 on 2024-12-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_comment_attachment_participation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ()},
        ),
    ]
