# Generated by Django 5.1.2 on 2024-12-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
    ]
