# Generated by Django 5.1.2 on 2024-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'default_permissions': (), 'permissions': [('add_attachment', 'Can add attachment'), ('view_attachment', 'Can view attachment')]},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'default_permissions': (), 'permissions': [('add_comment', 'Can add comment'), ('view_comment', 'Can view comment')]},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': (), 'permissions': [('add_event', 'Can add event'), ('view_event', 'Can view event'), ('register_event', 'Can register for event'), ('comment_event', 'Can comment on event')]},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'default_permissions': (), 'permissions': [('add_participation', 'Can add participation'), ('view_participation', 'Can view participation')]},
        ),
    ]
