# Generated by Django 5.1.2 on 2024-12-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
